name: "Voltronic Inverter GCC Fix"
version: "1.0.2"
slug: "voltronic_gcc_fix"
description: "Versión corregida para fallos de compilación std::string"
arch:
  - aarch64
  - amd64
startup: services
boot: auto
map:
  - config:rw
options:
  device: "/dev/ttyUSB0"
schema:
  device: str
